### ISSUE TITLE
No Gyro though all required sensors equipped

### ISSUE THREAD

**Issue by Christian-1980** [artyom-beilis/skyhopper#23]
Hi __ though my smartphone has a gravity and gyroscope, the skyhopper displays no Gyro. Also the values in altitude do not change.

I am using Android 12 release July 2023 and a Motorola Moto G30. 

Any hint what I can do about it?

Cheers

**Comment by artyom-beilis** [comment]
check if browser has permissions to access the sensors.

What browser do you use? Try switching, try firefox or try chrome

**Comment by artyom-beilis** [comment]
One thing I noticed that your phone doesn't have compass. Chrome uses compass but I know that Firefox don't. 

So try Firefox. Note you need to swipe the screen left right to get to alignment star for a *firs* alignment

**Comment by Christian-1980** [comment]
Awesome for the quick response and hint! I checked with Firefox and it works so far! __ by the way nice job and I think it is a tool to bring astronomy to the people. I am planning to incorporate as standard it into my diy Dobson :-)

**Comment by artyom-beilis** [comment]
Ok, awesome.

Can you check other browsers and permissions so I can update manual to use firefox if compass is missing
