### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by kkaarreell** [artyom-beilis/skyhopper#28]
There Is a workarounds for switching android Chrome into a fullscreen described at 
https://android.stackexchange.com/questions/175329/force-fullscreen-mode-in-chrome-for-android
but it would be nice to have a support in AstroHopper itself.

Great app btw, thanks a ton!

**Comment by artyom-beilis** [comment]
From what I remember - you can't request full screen access in browser automatically for security reason.

AFAIR You need to have a user action triggering full screen.

**Comment by artyom-beilis** [comment]
If you find it otherwise please reopen the ticket

**Comment by artyom-beilis** [comment]
And I assume you probably missed: Settings -> "Full S." checkbox - it means full screen

**Comment by kkaarreell** [comment]
> And I assume you probably missed: Settings -> "Full S." checkbox - it means full screen

Yes , thats exactly what I wanted. Cool. Sorry for the noise.
